import type { Poster } from '../types/poster';
import { generatePosterGraphic } from '../utils/posterGraphicGenerator';

export const INITIAL_DEMO_POSTERS: Poster[] = [
  {
    id: 'demo-1',
    title: 'Rendezvous 26 Official Festival Emblem Poster',
    slug: 'rendezvous-26-official-festival-emblem-poster',
    description: 'Official main stage theme poster for Badrul Huda Life Festival Rendezvous 26: Decoding Phytolore.',
    category: 'Events',
    eventName: 'Badrul Huda Life Festival',
    tags: ['rendezvous26', 'phytolore', 'mainstage', 'wayanad', 'life-festival'],
    posterUrl: generatePosterGraphic('Rendezvous 26 Main Stage', 'Events', 'Badrul Huda Life Festival', '#1B9B53', 'DECODING PHYTOLORE'),
    storagePath: 'posters/2026/september/rendezvous-26-main.svg',
    thumbnailUrl: generatePosterGraphic('Rendezvous 26 Main Stage', 'Events', 'Badrul Huda Life Festival', '#1B9B53', 'DECODING PHYTOLORE'),
    uploadedAt: new Date('2026-09-01T10:00:00Z').toISOString(),
    updatedAt: new Date('2026-09-01T10:00:00Z').toISOString(),
    eventDate: '2026-09-10',
    isFeatured: true,
    isPublished: true,
    downloadCount: 342,
    shareCount: 189
  },
  {
    id: 'demo-2',
    title: 'Grand Calligraphy Championship Results',
    slug: 'grand-calligraphy-championship-results',
    description: 'Official result announcement for the Senior Category Arabic & Botanical Calligraphy Competition at Rendezvous 26.',
    category: 'Results',
    eventName: 'Calligraphy Championship',
    tags: ['results', 'calligraphy', 'competition', 'winner', 'arabic-art'],
    posterUrl: generatePosterGraphic('Grand Calligraphy Winners', 'Results', 'Calligraphy Championship', '#2C365E', 'CHAMPIONSHIP RESULT'),
    storagePath: 'posters/2026/september/calligraphy-results.svg',
    thumbnailUrl: generatePosterGraphic('Grand Calligraphy Winners', 'Results', 'Calligraphy Championship', '#2C365E', 'CHAMPIONSHIP RESULT'),
    uploadedAt: new Date('2026-09-02T14:30:00Z').toISOString(),
    updatedAt: new Date('2026-09-02T14:30:00Z').toISOString(),
    eventDate: '2026-09-10',
    isFeatured: true,
    isPublished: true,
    downloadCount: 521,
    shareCount: 278
  },
  {
    id: 'demo-3',
    title: 'Phytolore Eco-Exhibition Showcase',
    slug: 'phytolore-eco-exhibition-showcase',
    description: 'Special program announcement for the Phytolore Botanical & Heritage Exhibition at Badrul Huda Academy.',
    category: 'Programs',
    eventName: 'Eco Heritage Exhibition',
    tags: ['phytolore', 'botanical', 'exhibition', 'wayanad', 'nature'],
    posterUrl: generatePosterGraphic('Phytolore Eco Exhibition', 'Programs', 'Eco Heritage Exhibition', '#25B45B', 'SPECIAL PROGRAM'),
    storagePath: 'posters/2026/september/eco-exhibition.svg',
    thumbnailUrl: generatePosterGraphic('Phytolore Eco Exhibition', 'Programs', 'Eco Heritage Exhibition', '#25B45B', 'SPECIAL PROGRAM'),
    uploadedAt: new Date('2026-09-02T18:00:00Z').toISOString(),
    updatedAt: new Date('2026-09-02T18:00:00Z').toISOString(),
    eventDate: '2026-09-11',
    isFeatured: true,
    isPublished: true,
    downloadCount: 289,
    shareCount: 145
  },
  {
    id: 'demo-4',
    title: 'Elocution & Public Speaking Results',
    slug: 'elocution-public-speaking-results',
    description: 'Official scoreboard and prize winners for the English & Malayalam Elocution contests.',
    category: 'Results',
    eventName: 'Literary Festival',
    tags: ['results', 'elocution', 'literary', 'speaking', 'winners'],
    posterUrl: generatePosterGraphic('Elocution Contest Results', 'Results', 'Literary Festival', '#D97706', 'PRIZE WINNERS'),
    storagePath: 'posters/2026/september/elocution-results.svg',
    thumbnailUrl: generatePosterGraphic('Elocution Contest Results', 'Results', 'Literary Festival', '#D97706', 'PRIZE WINNERS'),
    uploadedAt: new Date('2026-09-03T09:15:00Z').toISOString(),
    updatedAt: new Date('2026-09-03T09:15:00Z').toISOString(),
    eventDate: '2026-09-10',
    isFeatured: false,
    isPublished: true,
    downloadCount: 198,
    shareCount: 88
  },
  {
    id: 'demo-5',
    title: 'Cultural Night & Qawwali Schedule',
    slug: 'cultural-night-qawwali-schedule',
    description: 'Schedule for the Rendezvous 26 Grand Cultural Evening and traditional musical performances.',
    category: 'Events',
    eventName: 'Rendezvous Cultural Night',
    tags: ['events', 'qawwali', 'cultural-night', 'music', 'schedule'],
    posterUrl: generatePosterGraphic('Grand Cultural Night', 'Events', 'Rendezvous Cultural Night', '#1E2848', 'EVENT SCHEDULE'),
    storagePath: 'posters/2026/september/cultural-night.svg',
    thumbnailUrl: generatePosterGraphic('Grand Cultural Night', 'Events', 'Rendezvous Cultural Night', '#1E2848', 'EVENT SCHEDULE'),
    uploadedAt: new Date('2026-09-03T11:45:00Z').toISOString(),
    updatedAt: new Date('2026-09-03T11:45:00Z').toISOString(),
    eventDate: '2026-09-11',
    isFeatured: true,
    isPublished: true,
    downloadCount: 412,
    shareCount: 210
  },
  {
    id: 'demo-6',
    title: 'Quran Recitation & Tajweed Final Results',
    slug: 'quran-recitation-tajweed-final-results',
    description: 'Final published scores and top positions for the Hifz & Tajweed competitions.',
    category: 'Results',
    eventName: 'Recitation Grand Finale',
    tags: ['results', 'quran', 'tajweed', 'hifz', 'winners'],
    posterUrl: generatePosterGraphic('Recitation Grand Finale', 'Results', 'Recitation Competition', '#1B9B53', 'FINAL RESULTS'),
    storagePath: 'posters/2026/september/quran-results.svg',
    thumbnailUrl: generatePosterGraphic('Recitation Grand Finale', 'Results', 'Recitation Competition', '#1B9B53', 'FINAL RESULTS'),
    uploadedAt: new Date('2026-09-03T15:00:00Z').toISOString(),
    updatedAt: new Date('2026-09-03T15:00:00Z').toISOString(),
    eventDate: '2026-09-10',
    isFeatured: true,
    isPublished: true,
    downloadCount: 630,
    shareCount: 395
  },
  {
    id: 'demo-7',
    title: 'Registration Open for Quiz Championship',
    slug: 'registration-open-quiz-championship',
    description: 'Announcement poster for team registrations for the Grand Life & Science Quiz.',
    category: 'Announcements',
    eventName: 'Life Festival Quiz',
    tags: ['announcement', 'quiz', 'registration', 'competition'],
    posterUrl: generatePosterGraphic('Grand Quiz Registration', 'Announcements', 'Life Festival Quiz', '#F59E0B', 'REGISTER NOW'),
    storagePath: 'posters/2026/september/quiz-announcement.svg',
    thumbnailUrl: generatePosterGraphic('Grand Quiz Registration', 'Announcements', 'Life Festival Quiz', '#F59E0B', 'REGISTER NOW'),
    uploadedAt: new Date('2026-09-03T16:20:00Z').toISOString(),
    updatedAt: new Date('2026-09-03T16:20:00Z').toISOString(),
    eventDate: '2026-09-10',
    isFeatured: false,
    isPublished: true,
    downloadCount: 140,
    shareCount: 64
  },
  {
    id: 'demo-8',
    title: 'Rendezvous 26 Highlights & Memories',
    slug: 'rendezvous-26-highlights-memories',
    description: 'Commemorative highlight compilation poster honoring participating academies and students.',
    category: 'Highlights',
    eventName: 'Badrul Huda Life Festival',
    tags: ['highlights', 'memories', 'rendezvous26', 'academy'],
    posterUrl: generatePosterGraphic('Rendezvous 26 Highlights', 'Highlights', 'Badrul Huda Life Festival', '#2C365E', 'FESTIVAL MEMORIES'),
    storagePath: 'posters/2026/september/highlights.svg',
    thumbnailUrl: generatePosterGraphic('Rendezvous 26 Highlights', 'Highlights', 'Badrul Huda Life Festival', '#2C365E', 'FESTIVAL MEMORIES'),
    uploadedAt: new Date('2026-09-03T17:00:00Z').toISOString(),
    updatedAt: new Date('2026-09-03T17:00:00Z').toISOString(),
    eventDate: '2026-09-11',
    isFeatured: true,
    isPublished: true,
    downloadCount: 310,
    shareCount: 165
  }
];
